# Generated by Django 5.2.9 on 2025-12-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Any specific topics or questions"
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("one_to_one", "1-to-1 (£60/hr)"),
                            ("two_students", "2 Students (£100/hr)"),
                            ("three_students", "3 Students (£120/hr)"),
                        ],
                        default="one_to_one",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("face_to_face", "Face-to-Face"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True,
                        help_text="Zoom/Google Meet link for online sessions",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Address for face-to-face sessions",
                        max_length=200,
                    ),
                ),
                ("price", models.PositiveIntegerField(help_text="Price in pence")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="BookingNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topics_covered",
                    models.TextField(help_text="What was covered in the session"),
                ),
                (
                    "homework",
                    models.TextField(
                        blank=True, help_text="Homework or practice exercises"
                    ),
                ),
                (
                    "next_session",
                    models.TextField(blank=True, help_text="Topics for next session"),
                ),
                ("student_feedback", models.TextField(blank=True)),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("max_students", models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
            },
        ),
    ]
