# Generated by Django 5.2.9 on 2025-12-13 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="additional_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional students for group sessions",
                related_name="group_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific topic to cover",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.topic",
            ),
        ),
        migrations.AddField(
            model_name="bookingnote",
            name="booking",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_note",
                to="bookings.booking",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("day_of_week", "start_time")},
        ),
    ]
